### PR TITLE
Make light badge2

### PR DESCRIPTION
**Pull request by Ealdwulf**
@skarbat This has the commits from your PR, and also the notification version of the badge.
I'm making a new PR because there was a merge conflict.

### CODE REVIEW

**Comment by skarbat** [comment]
Wonderful @Ealdwulf thanks! I have just pushed a PR for make-light to integrate with it:

 * https://github.com/KanoComputing/kano-powerup/pull/111

**Comment by skarbat** [comment]
@alex5imon @convolu do you think we can merge this?
We will need to build kano-profile on scratch otherwise we won't be able to test powerup-kit.

**Comment by convolu** [comment]
Of course you can merge. Just keep in mind that until the release we will bump the package version as more things are added. For the locked assets is the alpha level same as the one that we use for the others. If not it may look a bit weird when it is displayed next to a locked item. If you didn't manually generate them then it should be ok

**Comment by Ealdwulf** [comment]
@convolu I ran the script which automatically generates the '_locked.png' versions - was that correct?

**Comment by convolu** [comment]
@Ealdwulf yes that is great. I see you actually added a comment with the dependencies, that is very helpful.

Looks good to me :shipit:

**Pull request merged**
