### PR TITLE
Adding new badge for Make Light challenges completion

### PR DESCRIPTION
**Pull request by skarbat**

### CODE REVIEW

**Comment by alex5imon** [comment]
@skarbat you need to add the locked version of the asset and run this script to generate the different images: https://github.com/KanoComputing/kano-profile/blob/master/media/images/badges/generate-images.sh

**Comment by Ealdwulf** [comment]
@skarbat Presumably we need to bump the version in debian/changelog and depend on it in powerup-kit?

**Comment by convolu** [comment]
What is the status of this? Do we still need it?

**Comment by Ealdwulf** [comment]
Oops, I thought this had been merged. Yes, we still need it.

**Comment by Ealdwulf** [comment]
@convolu On further checking, actually all these changes are already merged.

**Pull request closed without merging**
