### PR TITLE
Correct method name remove_items->remove_all.

### PR DESCRIPTION
**Pull request by Ealdwulf**
This is a call to a nonexistent method, I think this is the one meant. Spotted on jessie, but I don't think it's a jessie issue.
@carolineclark @pazdera

### CODE REVIEW

**Comment by convolu** [comment]
Bump

**Comment by pazdera** [comment]
I haven't been involved in this so I'd leave it for @carolineclark to review.

**Comment by convolu** [comment]
`self._day_dropdown` is an instance of `KanoComboBox ` which has the method mentioned in the commit (see [here](https://github.com/KanoComputing/kano-toolset/blob/master/kano/gtk3/kano_combobox.py#L240)).

This looks good.

**Comment by carolineclark** [comment]
Oops my bad.
I don't think there is a need to pull request if the original is broken otherwise. :P
:shipit:

**Comment by convolu** [comment]
Thanks @Ealdwulf, @carolineclark . Merging

**Pull request merged**
