### PR TITLE
[OS-293] Fix kano-toolset dependency version (Jessie)

### PR DESCRIPTION
**Pull request by radujipa**
This fixes an issue with importing touch() function from kano-toolset
which was added in 3.15.0. The package dependency now reflects this
newer version. **This change is for Jessie.**

### CODE REVIEW

**Comment by radujipa** [comment]
@skarbat Just fixed the `jessie` branch to reflect `Beta-v3.15.0` tag. The PR should look normal now :)

**Comment by skarbat** [comment]
Allright! 👍  @radujipa :)

**Comment by skarbat** [comment]
I think there's a typo somewhere in the dependencies... from the logs:

```dr info debuild dpkg-source: warning: can't parse dependency libkano-python-dev
dr info debuild    libkdesk-dev
```

**Comment by radujipa** [comment]
Thanks @skarbat! Missing comma... >_>

**Pull request merged**
