### PR TITLE
kano-sync: Fixing restore issue

### PR DESCRIPTION
**Pull request by pazdera**
Related to: https://github.com/KanoComputing/peldins/issues/2246

The question is, how did this ever work?

cc @convolu @tombettany @alex5imon

### CODE REVIEW

**Comment by alex5imon** [comment]
Ha! I haven't heard that one before @pazdera

**Comment by convolu** [comment]
Maybe jessie tar brought this to the surface?

@pazdera  Just out of curiosity, the `k` argument is for not deleting existing files that the archive doesn't have a replacement for but the `--overwrite` will make it actually replace the ones that it does have a replacement for?

**Comment by pazdera** [comment]
@convolu That's a good point ... I guess that's not needed any more.

**Comment by pazdera** [comment]
It also depends on the policy we want, I guess. Is the restore meant to just fill in stuff you don't have or restore full backup from Kano World?

Personally, I think restoring all is safer as with getting just some files, we might end up in a weird state of having a combination of old and new ...

**Comment by pazdera** [comment]
Removed the flag, do you guys agree with the get-everything-from-the-server policy then?

**Comment by convolu** [comment]
I think that restoring from server is a good strategy

Looks ok to me :shipit:

**Pull request merged**
