### PR TITLE
Limit the number of world notifications displayed at the same time

### PR DESCRIPTION
**Pull request by pazdera**
Related to: https://github.com/KanoComputing/peldins/issues/2081

cc @alex5imon @convolu @tombettany

### CODE REVIEW

**Comment by pazdera** [comment]
bump

**Comment by Ealdwulf** [comment]
Will it do 5 per call to sync, or drop the rest?

**Comment by pazdera** [comment]
@Ealdwulf It should show the newest 5 per call to sync.

**Comment by convolu** [comment]
Looks ok to me :+1:

**Comment by Ealdwulf** [comment]
That's when the screensaver kicks in, not every 20 minutes, right? If so
looks good to me too.

**Pull request merged**
